"""Ajout de la table reservations

Revision ID: 14acc140e737
Revises: e00c574d07d0
Create Date: 2025-02-24 14:08:18.298564

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '14acc140e737'
down_revision = 'e00c574d07d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('horaire', sa.String(length=5), nullable=False),
    sa.Column('nombre_couverts', sa.Integer(), nullable=False),
    sa.Column('code_reservation', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_reservation')
    )
    op.create_table('commandes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom_client', sa.String(length=100), nullable=False),
    sa.Column('plats', sa.JSON(), nullable=False),
    sa.Column('heure_retrait', sa.String(length=5), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('code_reservation', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['code_reservation'], ['reservations.code_reservation'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantite_disponible', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('temps_preparation', sa.Integer(), nullable=False))
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               nullable=False)
        batch_op.drop_index('nom')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.create_index('nom', ['nom'], unique=True)
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('temps_preparation')
        batch_op.drop_column('quantite_disponible')

    op.drop_table('commandes')
    op.drop_table('reservations')
    # ### end Alembic commands ###
