"""Ajout des tables

Revision ID: 7bc55646b055
Revises: 
Create Date: 2025-02-14 12:29:39.415815

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7bc55646b055'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('prix', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('commandes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom_client', sa.String(length=100), nullable=False),
    sa.Column('plats', sa.JSON(), nullable=False),
    sa.Column('heure_retrait', sa.String(length=5), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('code_reservation', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['code_reservation'], ['reservations.code_reservation'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('horaire', sa.String(length=5), nullable=False))
        batch_op.alter_column('date',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.drop_column('heure')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('heure', mysql.VARCHAR(length=5), nullable=False))
        batch_op.alter_column('date',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('horaire')

    op.drop_table('commandes')
    op.drop_table('menu')
    # ### end Alembic commands ###
