"""empty message

Revision ID: 8d87db1e4c2f
Revises: e00c574d07d0
Create Date: 2025-02-21 14:41:02.096289

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8d87db1e4c2f'
down_revision = 'e00c574d07d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('prix', sa.Float(), nullable=False),
    sa.Column('quantite_disponible', sa.Integer(), nullable=False),
    sa.Column('temps_preparation', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commande_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commande_id', sa.Integer(), nullable=False),
    sa.Column('plat_id', sa.Integer(), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('prix_total', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['commande_id'], ['commandes.id'], ),
    sa.ForeignKeyConstraint(['plat_id'], ['menus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.drop_index('nom')

    op.drop_table('menu')
    with op.batch_alter_table('commandes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commandes', schema=None) as batch_op:
        batch_op.drop_column('total')

    op.create_table('menu',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nom', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('prix', mysql.FLOAT(), nullable=False),
    sa.Column('quantite_disponible', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('temps_preparation', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.create_index('nom', ['nom'], unique=True)

    op.drop_table('commande_items')
    op.drop_table('menus')
    # ### end Alembic commands ###
