"""Correction des modèles

Revision ID: bd358641d0c8
Revises: 
Create Date: 2025-03-05 17:08:56.920596

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bd358641d0c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('horaire', sa.String(length=5), nullable=False),
    sa.Column('nombre_couverts', sa.Integer(), nullable=False),
    sa.Column('code_reservation', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_reservation')
    )
    op.create_table('commande_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commande_id', sa.Integer(), nullable=False),
    sa.Column('plat_id', sa.Integer(), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('prix_total', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['commande_id'], ['commandes.id'], ),
    sa.ForeignKeyConstraint(['plat_id'], ['menus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('commandes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plats', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('statut', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('code_reservation', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('nom_client',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('heure_retrait',
               existing_type=mysql.TIME(),
               type_=sa.String(length=5),
               existing_nullable=False)
        batch_op.alter_column('total',
               existing_type=mysql.DECIMAL(precision=6, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'reservations', ['code_reservation'], ['code_reservation'])
        batch_op.drop_column('details')
        batch_op.drop_column('date_retrait')
        batch_op.drop_column('horaire')

    with op.batch_alter_table('menus', schema=None) as batch_op:
        batch_op.alter_column('nom',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('prix',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menus', schema=None) as batch_op:
        batch_op.alter_column('prix',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=5, scale=2),
               existing_nullable=False)
        batch_op.alter_column('type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('nom',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('commandes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('horaire', mysql.VARCHAR(length=5), nullable=False))
        batch_op.add_column(sa.Column('date_retrait', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('details', mysql.JSON(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('total',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=6, scale=2),
               existing_nullable=False)
        batch_op.alter_column('heure_retrait',
               existing_type=sa.String(length=5),
               type_=mysql.TIME(),
               existing_nullable=False)
        batch_op.alter_column('nom_client',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('code_reservation')
        batch_op.drop_column('statut')
        batch_op.drop_column('plats')

    op.drop_table('commande_items')
    op.drop_table('reservations')
    # ### end Alembic commands ###
