"""Ajout de la quantité et du temps de préparation aux menus

Revision ID: e00c574d07d0
Revises: 7bc55646b055
Create Date: 2025-02-18 15:25:25.853470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e00c574d07d0'
down_revision = '7bc55646b055'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantite_disponible', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('temps_preparation', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.drop_column('temps_preparation')
        batch_op.drop_column('quantite_disponible')

    # ### end Alembic commands ###
